console.log("Practica Clase 3 - Guia de ejercicios ES6");
console.log("Ejercicio 2: Arrays Operaciones basicas");
console.log("a) anañdir un elemento al inicio y final del array");
const frutas = ["manzana", "banana", "naranja"];
console.log("Frutas iniciales:", frutas);
frutas.unshift("pera");
console.log("Frutas despues de agregar uva:", frutas);
frutas.push("uva");
console.log("Frutas despues de insertar pera en la posicion 1:", frutas);
console.log("b) dado un array crear otro igual pero con el doble de cada numero");
const numeros = [1, 2, 3, 4, 5];
const numerosdobles = numeros.map(num => num * 2);
console.log("Numeros iniciales:", numeros);
console.log("Numeros dobles:", numerosdobles);
console.log("c) cre 2 arrays de colores y unelos con concat()");
const colores1 = ["rojo", "verde", "azul"];
const colores2 = ["bordo", "celeste"];
const coloresCombinado = colores1.concat(colores2);
console.log("Colores 1:", colores1);
console.log("Colores 2:", colores2);
console.log("Colores combinados:", coloresCombinado);
console.log("d) eliminar primero y ultimo en un array");
const elementos = ["agua", "fuego", "tierra", "aire", "plasma"];
console.log("Elementos iniciales:", elementos);
elementos.pop();
console.log("Elementos despues de eliminar el ultimo:", elementos);
elementos.shift();
console.log("Elementos despues de eliminar el primero:", elementos);